# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58cfc6a5a962664d328245f51192d6f841765a0d1181ee12cf06d454d6dfcb40362e46e364dfaf852b2788e8e6f4455add863ae5a3cda8c87b1f148defd53860

test:
  secret_key_base: f30e638b65780d9e760f31b041bc6f85db51b908bfd8015da0f410ba62ece226498ee1b2791f2bdb13d36491d0140929618dc3ffa0e578dae27eded0547677a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
